version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - node_modules:/var/www/html/node_modules
        networks:
            - laravel_network
        depends_on:
            - db
        ports:
            - "9000:9000"
            - "5173:5173" # Vite dev server port

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

    db:
        image: postgres:15-alpine
        container_name: laravel_postgres
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel_network

volumes:
    pgdata:
    node_modules:

networks:
    laravel_network:
        driver: bridge
